# kind load docker-image us-central1-docker.pkg.dev/prj-common-l-shared-73205/gabriel-dev-reg/pluggable-components:1.0 --name conductor-dp-kkxolw9h
# kind load docker-image hello:1.0 --name conductor-dp-kkxolw9h
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "my-app"
    spec:
      volumes: ## required, the sockets volume
        - name: dapr-unix-domain-socket
          emptyDir: {}
      containers:
        ### application code
        - name: app
          image: hello:1.0