# kind load docker-image us-central1-docker.pkg.dev/prj-common-l-shared-73205/gabriel-dev-reg/pluggable-components:1.0 --name conductor-dp-ys4htn4h
# kind load docker-image hello:1.0 --name conductor-dp-ys4htn4h
# kubectl apply -f "http://localhost:30004/apis/diagrid.io/v1beta1/clusters/fdfbe207-e6c8-4827-bd5a-6f64dbc3eda1/manifests?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZXMiOlsicmVhZDptYW5pZmVzdCJdLCJodHRwczovL2RpYWdyaWQuaW8vb3JnSWQiOiJiMmE3NmIyNi1jYTQ1LTQ2ODYtYTdiZC0zNWNlNTk2ZDkyZTMiLCJpYXQiOjE2NzI1ODg5MzgsImV4cCI6MTY3MjY3NTMzOCwiYXVkIjoidXJuOmFkbWluZ3JpZCIsImlzcyI6ImRpYWdyaWQuaW8iLCJzdWIiOiJhdXRoMHw2Mzk4ZTQ1MTg2OGMwNmQ1OTcyMmQ4MTkiLCJqdGkiOiJzN2ZoOWdiMzZ4NWk4MmllbHlwdGYifQ.96krsRRYuE2L1oItdWMLzZfDlsMmzH0d9KANsariw8I"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: pcomp
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "my-app"
        dapr.io/unix-domain-socket-path: "/tmp/dapr-components-sockets" ## required, the default path where Dapr uses for registering components.
        dapr.io/sidecar-liveness-probe-delay-seconds: "30"
        dapr.io/log-level: "debug"
    spec:
      volumes: ## required, the sockets volume
        - name: dapr-unix-domain-socket
          emptyDir: {}
      containers:
        ### application code
        - name: myapplication
          image: docker.io/famargon/plugabble-component-app-2eefd739e07c9540acfb54e1e30cfc26:latest
        ### This is the pluggable component container.
        - name: component
          image: docker.io/famargon/server-a23f0fe2ad2ebd1a9bb76b992dd7684a@sha256:b267e63271308385e9857f7a8fbfaaa346ae0bfcc3f9c54074671f712e46db7d
          volumeMounts: # required, the sockets volume mount
            - name: dapr-unix-domain-socket
              mountPath: /tmp/dapr-components-sockets
